In [1]:
bs = ['balance sheet as on' ,
'balance sheets',
'condensed consolidated balance sheets',
'condensed consolidated statements of financial position',
'consolidated and company balance sheets',
'consolidated balance sheet',
'consolidated balance sheets',
'consolidated balance sheets unaudited',
'consolidated condensed balance sheets',
'consolidated statement of financial position',
'consolidated statements of financial condition',
'consolidated statements of financial position unaudited',
'group statement of financial position',
'statement of financial position',
'statement of financial position as at',
 'unaudited condensed consolidated balance sheets',
  'equity',
 'liabilities', 
      'assets']
cf = ['condensed consolidated statements of cash flows',
'condensed consolidated statements of cash flows unaudited',
'consolidated cash flow statement',
'consolidated condensed statements of cash flows',
'consolidated statement of cash flows',
'consolidated statements of cash flows',
'consolidated statements of cash flows unaudited',
'consolidated statements of cash flows unaudited',
'group statement of cash flows',
'statement of cash flow',
'statement of cash flows for the year ended' ,
'statement of cash flows for the year ended',
'statement of consolidated cash flows',
'unaudited condensed consolidated statements of cash flows']

pl = ['condensed consolidated statements of operations',
'consolidated income statement',
'consolidated income statements',
'consolidated profit and loss account',
'consolidated statement of comprehensive income',
'consolidated statement of profit and loss',
'consolidated statements of income',
'consolidated statements of operations',
'group statement of comprehensive income',
'statement of comprehensive income',
'statement of financial activities for the year ended',
'statemnent of profit and loss for the year ended',
'unaudited condensed consolidated statements of loss']

In [2]:
import pandas as pd

In [8]:
pd.DataFrame(bs)

                                                    0
0                                 balance sheet as on
1                                      balance sheets
2               condensed consolidated balance sheets
3   condensed consolidated statements of financial...
4             consolidated and company balance sheets
5                          consolidated balance sheet
6                         consolidated balance sheets
7               consolidated balance sheets unaudited
8               consolidated condensed balance sheets
9        consolidated statement of financial position
10     consolidated statements of financial condition
11  consolidated statements of financial position ...
12              group statement of financial position
13                    statement of financial position
14              statement of financial position as at
15    unaudited condensed consolidated balance sheets
16                                             equity
17                                        liabilities
18                                             assets